### ISSUE TITLE
Boot email report exception when there are lab conflicts

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-backend#115]
When generating a boot email report, if there are any conflicts between labs this exception is raised:
```
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: [   ERROR/MainThread] Task send-boot-report[a53c746a-b1d6-4bad-8e38-e183fcfc170b] raised unexpected: AttributeError("'NoneType' object has no attribute 'viewkeys'",)
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: Traceback (most recent call last):
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: File "/srv/.venv/staging-api.kernelci.org/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: R = retval = fun(*args, **kwargs)
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: File "/srv/.venv/staging-api.kernelci.org/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: return self.run(*args, **kwargs)
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: File "/srv/staging-api.kernelci.org/app/taskqueue/tasks/report.py", line 58, in send_boot_report
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: mail_options=taskc.app.conf.get("mail_options", None)
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: File "/srv/staging-api.kernelci.org/app/utils/report/boot.py", line 477, in create_boot_report
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: txt_body, html_body, subject = _create_boot_email(boot_data)
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: File "/srv/staging-api.kernelci.org/app/utils/report/boot.py", line 999, in _create_boot_email
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: boot_data["platforms"] = _parse_and_structure_results(boot_data)
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: File "/srv/staging-api.kernelci.org/app/utils/report/boot.py", line 1297, in _parse_and_structure_results
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: conflict_data, conflict_struct["data"], is_conflict=True)
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: File "/srv/staging-api.kernelci.org/app/utils/report/boot.py", line 1164, in _traverse_data_struct
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: for lab in def_get(board).viewkeys():
Feb 14 12:59:29 ip-172-30-0-172 kernelci-celery[64550]: AttributeError: 'NoneType' object has no attribute 'viewkeys'
```

It looks like the `if is_conflict:` branch in the code hasn't been updated to deal with the build environment level in the data structures.

**Comment by gctucker** [comment]
See #126 to work around this issue until a fix can be merged.  This has been going on for too long, we're missing important boot reports and bisections.

**Comment by gctucker** [comment]
This issue has now been properly fixed.
