### ISSUE TITLE
boot regression errors with empty db

### ISSUE THREAD

**Issue by khilman** [kernelci/kernelci-backend#148]
testing a fresh install of the backend (master branch) and testing using the fake-callback helper script, but seeing this:
```
[ WARNING/MainThread] No job document found for boot stable-linux-5.0.y-v5.0.21-multi_v7_defconfig (arm)
[ WARNING/MainThread] No build document found for boot stable-linux-5.0.y-v5.0.21-multi_v7_defconfig (arm)
[   ERROR/MainThread] Task boot-regressions[9608fec3-b0cb-4209-a3cb-fedb02803815] raised unexpected: TypeError("'NoneType' object has no attribute '_
_getitem__'",)                                                                                                                                      
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/kernelci-backend/app/taskqueue/tasks/boot.py", line 46, in find_regression
    utils.boot.regressions.find(boot_doc_id, taskc.app.conf.db_options)
  File "/home/user/kernelci-backend/app/utils/boot/regressions.py", line 438, in find
    return check_and_track(boot_doc, db_options)
  File "/home/user/kernelci-backend/app/utils/boot/regressions.py", line 348, in check_and_track
    last_boot_spec = {k: last_boot_doc[k] for k in BOOT_SPEC_KEYS}
  File "/home/user/kernelci-backend/app/utils/boot/regressions.py", line 348, in <dictcomp>
    last_boot_spec = {k: last_boot_doc[k] for k in BOOT_SPEC_KEYS}
TypeError: 'NoneType' object has no attribute '__getitem__'
[   ERROR/MainThread] Task failed, UUID: 9608fec3-b0cb-4209-a3cb-fedb02803815, error: 'NoneType' object has no attribute '__getitem__'
[ WARNING/MainThread] No test results
```

This patch appears to fix, but not sure if this is the proper db check:
```
diff --git a/app/utils/boot/regressions.py b/app/utils/boot/regressions.py
index 0f02d7c703a9..f57f64291af2 100644
--- a/app/utils/boot/regressions.py
+++ b/app/utils/boot/regressions.py
@@ -345,6 +345,9 @@ def check_and_track(boot_doc, db_options):
     boot_spec[models.KERNEL_KEY] = {"$ne": boot_doc[models.KERNEL_KEY]}
     last_boot_doc = utils.db.find_one2(boot_collection, boot_spec,
                                        sort=[(models.CREATED_KEY, -1)])
+    if not last_boot_doc:
+        return None
+    
     last_boot_spec = {k: last_boot_doc[k] for k in BOOT_SPEC_KEYS}
```

**Comment by gctucker** [comment]
Boot tests have been dropped.  There is no known issue of this kind with test case regressions.
